import {useEffect, useState} from 'react'
import { useRouter,Router } from 'next/router'
import NProgress from 'nprogress'
import Head from "next/head";
import Link from "next/link";
import {BackTop} from 'antd'
import HeaderV1 from "../components/HeaderV1";
import 'antd/dist/antd.css'
import '../../styles/globals.css'
import 'nprogress/nprogress.css'
import 'antd/dist/antd.css';
// md样式
import '@kangc/v-md-editor/lib/style/base-editor.css';
import '@kangc/v-md-editor/lib/style/preview.css';
import '@kangc/v-md-editor/lib/theme/style/github.css';
import '@kangc/v-md-editor/lib/theme/style/vuepress.css';
import styles from "../../styles/Home.module.css";
function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const [isMobile,setIsMobile] = useState(false)
  useEffect(() => {
    Router.events.on("routeChangeStart", (url,{shallow}) => {
      console.log(
          `App is changing to ${url} ${
              shallow ? 'with' : 'without'
          } shallow routing`
      )
      NProgress.start();
    });
    router.events.on("routeChangeComplete", () => {
      NProgress.done();
    });
    router.events.on("routeChangeError", () => {
      NProgress.done();
    });
  }, []);
  useEffect(() => {
      if(window.navigator.userAgent.match(/(iPhone|iPod|Android|ios)/i)){
          setIsMobile(true)
      }else{
          setIsMobile(false)
      }
  },[])
  return (
      <>
        <Head>
          <title>Dun blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.container}>
            <HeaderV1 isMobile={isMobile} />
            <div className={styles.content}>
                <Component {...pageProps} />
            </div>

          <footer className={styles.footer}>
                <span>@copay</span><a href="www.dsdsa.com" target='_blank'>1556456456456</a>
          </footer>
            <BackTop>
                <div className={styles.backUp}>UP</div>
            </BackTop>
        </main>
      </>
  )
}

export default MyApp
