import { useEffect } from 'react'
import { useRouter,Router } from 'next/router'
import 'antd/dist/antd.css'
import '../styles/globals.css'
import 'nprogress/nprogress.css'
import NProgress from 'nprogress'
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
function MyApp({ Component, pageProps }) {
  const router = useRouter();
  useEffect(() => {
    Router.events.on("routeChangeStart", (url,{shallow}) => {
      console.log(
          `App is changing to ${url} ${
              shallow ? 'with' : 'without'
          } shallow routing`
      )
      NProgress.start();
    });
    router.events.on("routeChangeComplete", () => {
      NProgress.done();
    });
    router.events.on("routeChangeError", () => {
      NProgress.done();
    });
  }, []);
  return (
      <>
        <Head>
          <title>Dun blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Component {...pageProps} />
        </main>

        <footer className={styles.footer}>
          <span>@copay</span><a href="www.dsdsa.com" target='_blank'>1556456456456</a>
        </footer>
      </>
  )
}

export default MyApp
